name: CI App Builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libltdl-dev \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            python3 \
            python3-pip \
            python3-venv \
            libgl1-mesa-dev \
            mesa-common-dev

      - name: Build with Buildozer
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          python3 -m pip install buildozer
          echo "Cleaning buildozer cache and previous build artifacts..."
          rm -rf ~/.buildozer/ .buildozer/ .android/
          echo "Building Android APK..."
          yes | buildozer android debug

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install macOS Dependencies
      run: |
        brew install autoconf automake libtool pkg-config gmp ccache
        # Required for older Python recipes if targeting Android
        brew install openssl@3 

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Build with Buildozer
      run: |
        # Change 'ios' to 'android' or 'osx' depending on your target target platform
        buildozer ios debug
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packaged-app
        path: bin/
